### ISSUE TITLE
Create a new predefined robot

### ISSUE THREAD

**Issue by madureirabrazil** [nnadeau/pybotics#657]
Hello.
I would like to create a new predefined robot, but using classical DH parameters. Is it possible?

**Comment by nnadeau** [comment]
Not at the moment, but the structure to add additional `Link` models may be seen here: https://github.com/nnadeau/pybotics/blob/ff70719fc96d6617211006533d97acac51d54da0/pybotics/link.py#L69

Otherwise, MDH is currently supported, as defined from here:

```
Craig, John J. Introduction to robotics: mechanics and control. Vol. 3. Upper Saddle River, NJ, USA:: Pearson/Prentice Hall, 2005.
```

**Comment by madureirabrazil** [comment]
Thanks! I got it!
