### ISSUE TITLE
Defining a custom robot model [FEATURE]

### ISSUE THREAD

**Issue by MCYBA** [nnadeau/pybotics#735]
## User Story

For integrating `pybotics` into my physical robotic structure, I need to use a custom robot model definition.

## Potential Solutions

- A function that read a CSV file that contains D-H parameters, and returns the model Array.
- Instead of CSV files, parameters can be given directly as a list.

**Comment by nnadeau** [comment]
@MCYBA 

- if your robot is off-the-shelf (e.g., KUKA, ABB, UR, Fanuc), please make a pull request and add the robot model to [`pybotics/predefined_models.py`](https://github.com/nnadeau/pybotics/blob/master/pybotics/predefined_models.py)
- for a CSV file:

```python
import numpy as np
from pybotics.robot import Robot

# load csv data
my_data = np.genfromtxt('my_file.csv', delimiter=',')

# create robot object
robot = Robot.from_parameters(my_data)
```

**Comment by nnadeau** [comment]
@MCYBA how's it going?

**Comment by nnadeau** [comment]
Closing stale issue.
