### ISSUE TITLE
Create a way to add your own arm model[FEATURE]

### ISSUE THREAD

**Issue by thebossman1093** [nnadeau/pybotics#750]
## User Story

If there was a comment next to each line of one of the arrays containing the pre-trained model saying what exactly each value was supposed to represent, that would help.

I tried looking at the spec sheets of the arms and matching up values but I couldn't figure much out.

**Comment by nnadeau** [comment]
@thebossman1093 , these parameters and arrays correspond to the modified Denavit–Hartenberg parameters. This is a classic notation introduced by Craig in the textbook Introduction to Robotics. 

I added a link to the Wikipedia page in https://github.com/nnadeau/pybotics/pull/751

Does that help?
